### ISSUE TITLE
Add bash... completions to rtx tap

### ISSUE THREAD

**Issue by eugenesvk** [jdxcode/homebrew-tap#1]
Some cli tools auto-install completion files and add a post-install instructions on how to add said completion files to user configs
Would be nice to have the same with rtx to get the autoupdates

**Comment by jdx** [comment]
Related to this, we should add postinstall help telling people to add the activate hook to their rc

**Comment by jdx** [comment]
this is now done automatically: https://github.com/jdxcode/homebrew-tap/blob/main/rtx.rb#L32
